### 配置项目启动端口
server:
  port: 9999
spring:
  ### 配置项目应用名
  application:
    name: itrip
  ### 配置JDBC连接信息
  datasource:
    ### JDBC 连接驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    ### JDBC 连接URL
    url: jdbc:mysql://localhost:3306/itrip_db
    ### 数据库登录账户
    username: root
    ### 数据库登录密码
    password: 123456
    ### 采用Druid作为数据库连接池技术
    type: com.alibaba.druid.pool.DruidDataSource
    ### Druid数据库连接池配置信息
    druid:
      ### 最小连接数
      min-idle: 3
      ### 最大连接数
      max-active: 15
      ### 初始连接数
      initial-size: 5
      ### 最小存活时间
      min-evictable-idle-time-millis: 30000
      ### 最大存活时间
      max-evictable-idle-time-millis: 60000
### mybatis 配置信息
mybatis:
  mapper-locations: classpath:/mapper/*.Mapper.xml
  type-aliases-package: com.zarek.itrip.pojo.entity